### ISSUE TITLE
RaspberryPi support

### ISSUE THREAD

**Issue by thijstriemstra** [Ableton/m4l-connection-kit#11]
Would be nice to have support for RaspberryPi.

**Comment by lib-ableton** [comment]
Hi thijstriemstra,

Thanks for your input! Yes, I agree that RaspberryPi support would be very cool. We'll take your idea into consideration as a feature request.

In the meantime I'd suggest checking out the [Cycling '74 Forums](https://cycling74.com/forums/category/Max%20For%20Live/page/1), in case there are any threads on the topic that might be of interest to you.

If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) since this 'Issues' page is not regularly monitored.

Best regards,
Lillia
Max for Live Content Specialist
