### ISSUE TITLE
TouchOSC: A longer parameters list please?

### ISSUE THREAD

**Issue by JayDeLux** [Ableton/m4l-connection-kit#14]
Hello. Thank you for TouchOSC!
I am posting this here although it is not an "issue" as such.
To be honest I gave a try to M4L and went through their tutorials and videos .etc... but the learning curve is steep! I am not giving up, when I have some time I learn and try to make things work myself.
I tried to edit TouchOSC in M4L as I would like to have more parameters in the parameters list. As it stands there are 8, I could really do with 32 of them.
In M4L I copied/pasted the 8, I 'patched' similarly as how it was with the pre-existing parameters .etc... 
-_-
Could someone fix this for me and branch it? 
It would be much appreciated.

**Comment by JayDeLux** [comment]
I gave it another try this WE but the M4L learning curve is very steep and have not managed to create additional parameters in the existing list :-(  Anyone? I could post what I have done if you want to have a look...

**Comment by lib-ableton** [comment]
Hi JayDeLux,

We don't provide usability support for customizing M4L patches to suit your needs, but it's a cool idea nonetheless! We'll take it into consideration for future devices.

I'd suggest posting your question on the [Cycling '74 Forums](https://cycling74.com/forums/category/Max%20For%20Live/page/1). The community there is usually responsive, and I'm sure you could get some good pointers by uploading your patch.

We will soon be disabling this 'Issues' section, since the page is not regularly monitored. If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
