### ISSUE TITLE
Arduino MEGA support

### ISSUE THREAD

**Issue by noasilver** [Ableton/m4l-connection-kit#16]
Hi! I love this patch it makes it so easy for me to communicate with Ableton, but I have a problem. 

I need more analog connections as there is only 5. For my project I need at least 10 (preferably more) inputs. This is why I'm working with the Arduino MEGA. At the bottom there is the option to select Arduino UNO but that's the only option (this makes me believe you planned to do more). Now the patch recognises the MEGA just fine. Everything works but I don't have all the analog ins and outs that my board has. Would love it so much if you could extend the list so that all the ins and outs of Arduino mega are recognised in Live.

Noa

**Comment by lib-ableton** [comment]
Hi noasilver,

Thanks for your feedback! It would definitely be great to add the Arduino MEGA as an option for including more analog inputs. We'll take your idea into consideration.

In the meantime, you could always reach out to the community on the [Cycling '74 Forums](https://cycling74.com/forums/category/Max%20For%20Live/page/1), if you're looking to edit the Arduino M4L device on your end.

We will soon be disabling this 'Issues' section, since the page is not regularly monitored. If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
