### ISSUE TITLE
§Receive just the last message

### ISSUE THREAD

**Issue by tarrabass** [Ableton/m4l-connection-kit#17]
I just receive the last message on each frame 
i send 10 message and juste the last is analyse 
thnaks

**Comment by lib-ableton** [comment]
Hi tarabass,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
