### ISSUE TITLE
Provide a simple plugin that maps OSC from any source to parameters

### ISSUE THREAD

**Issue by alexanderwallin** [Ableton/m4l-connection-kit#19]
Hi there!

I've been looking around for a while now for a plugin that simply maps OSC messages from any source (in my case a piece of software) to parameters in Ableton. It would make a lot of sense for this kit to provide this, especially since it already deals with OSC in multiple ways.

Perhaps there is a way to achieve what I need using any of the existing plugins? If so, I'm happy to apply that and close this issue.

**Comment by lib-ableton** [comment]
Hi alexanderwallin,

Thanks for your input! I agree that this type of device would be useful, and we'll take your idea into consideration.

In the meantime I'd suggest reaching out to the community on the [Cycling '74 Forums](https://cycling74.com/forums/category/Max%20For%20Live/page/1), if you're feeling up to some Max patching. You could potentially hack the OSC TouchOSC device to be applicable on a larger scale, instead of being limited to use with the TouchOSC app.

If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) since this 'Issues' page is not regularly monitored.

Best regards,
Lillia
Max for Live Content Specialist

**Comment by alexanderwallin** [comment]
Thanks for the tips! I did throw together a very simple [Max4Live-OSC-Receiver](https://github.com/alexanderwallin/Max4Live-OSC-Receiver) plugin that does the trick. 🙂
