### ISSUE TITLE
JSON WEATHER dict @embed. writing new details cannot be saved

### ISSUE THREAD

**Issue by karlsadler** [Ableton/m4l-connection-kit#20]
I'm new to max really, but when I try to open and edit the dict file to add my own API and GPS coordinates, the file does not save or update, it either clears or resets to the details it previously had.

**Comment by karlsadler** [comment]
Managed to save it. slightly illogical, but just close down file's without saving the dict, but choose to make changes and save the actual max match. :0)

**Comment by lib-ableton** [comment]
Hi karlsadler,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If the JSON Weather issue persists, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
