### ISSUE TITLE
Leapmotion make Ableton Crashed

### ISSUE THREAD

**Issue by mousezhao** [Ableton/m4l-connection-kit#4]
Every time I tried to open the leapmotion device will make Ableton crash. Only Leapmotion, the rest of kit are good.

**Comment by crk-ableton** [comment]
Hi mousezhao, In this case please contact our support team via support@ableton.com - they'll request some data to investigate this...Thanks!

**Comment by lib-ableton** [comment]
Hi mousezhao,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If you need further assistance with the M4L Connection Kit, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
