### ISSUE TITLE
OSC MIDI Send also triggers on Note Off

### ISSUE THREAD

**Issue by vormplus** [Ableton/m4l-connection-kit#5]
Thank you for creating the Max for Live Connection Kit. These devices will be very useful for me.

I've just played a bit with the OSC MIDI Send device and noticed that a single note sends two OSC messages, one on Note On and one on Note Off.

This causes small glitches if you want to sync visuals in Processing to a 4/4 beat with 16th notes.

Possible solutions to fix this problem:
1. Only send a trigger on Note On.
2. Include Note On/Note Off as a boolean in the OSC message.

You can reproduce the problem with this Processing sketch. You'll notice that the circle vibrates a bit when you use 16th notes.

```
import oscP5.*;

OscP5 osc;

float r = 0;

void setup()
{
    size( 800, 600 );
    smooth( 8 );

    osc = new OscP5( this, 2346 );
}

void draw()
{
    background( 0 );
    translate( width/2, height/2 );

    noStroke();
    fill( 255 );
    ellipse( 0, 0, r, r );

    if ( r > 0 ) {
        r--;
    } 
}

void oscEvent( OscMessage msg )
{
    if ( msg.checkAddrPattern("/Note1") == true ) {
        r = 50;
    }
}
```

**Comment by lib-ableton** [comment]
Hi vormplus,

Thanks for bringing this to our attention!

We've filed this as a bug in our backlog. An eventual fix could be included as an update to the Connection Kit pack, although I can't provide any timeline guarantees.

We will soon be disabling this 'Issues' section, since the page is not regularly monitored. Please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) if you need further assistance with the M4L Connection Kit.

Best regards,
Lillia
Max for Live Content Specialist
