### ISSUE TITLE
Leap Motion open the help page every time I try to use the patch

### ISSUE THREAD

**Issue by balcooke** [Ableton/m4l-connection-kit#6]
I can get it to trigger MIDI notes but it also launches my browser with the help page multiple times as if I clicked on the 'Visit Website Tutorial' link

**Comment by lib-ableton** [comment]
Hi balcooke,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If the problem with the OSC Leap Motion device is still occurring, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) with a Status Report (Help > Get Support) for further investigation.

Best regards,
Lillia
Max for Live Content Specialist
