### ISSUE TITLE
Crash when mapping servo

### ISSUE THREAD

**Issue by merlinusambrosius** [Ableton/m4l-connection-kit#8]
Ableton Live 9.6.2, Max 7.2.2, getting a crash when mapping Servo to a macro in an Audio Effect.

**Comment by lib-ableton** [comment]
Hi merlinusambrosius,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If your Connection Kit devices are still crashing, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) with a Status Report (Help > Get Support).

Best regards,
Lillia
Max for Live Content Specialist
