### ISSUE TITLE
OSC Leap motion not working together with a Max Patcher with udpreceiver

### ISSUE THREAD

**Issue by aloisyang** [Ableton/m4l-connection-kit#9]
Hi guys,
Great device ! Thanks ! Everything works just find. 
However, I fail to make it work together: Ableton with Osc leap motion + A max Patcher receiving the same OSC port from ManosOsc. It either works only one side. But when I open the device in edit mode inside Max, both patcher receive the OSC messages. So, it must be possible as I desired, am I correct ?  Any advice will be much appreciated.
Cheers.
Alois.

**Comment by lib-ableton** [comment]
Hi aloisyang,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If the OSC Leap Motion issue persists, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
